# Generated by Django 2.2.12 on 2021-04-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Skill'},
        ),
    ]
