# Generated by Django 2.2.12 on 2021-04-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_auto_20210424_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
