# Generated by Django 2.2.12 on 2021-04-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20210424_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
    ]
