# Generated by Django 2.2.12 on 2021-04-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_auto_20210424_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
