# Generated by Django 2.2.12 on 2021-04-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_auto_20210425_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
