# Generated by Django 2.2.12 on 2021-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_auto_20210425_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/')),
                ('link', models.URLField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
