# Generated by Django 3.2.8 on 2021-10-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0012_remove_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
